# -*- coding: utf-8 -*-
"""extract_and_compute_vectors.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/
"""

# =============================================================================
# COLAB SETUP
# =============================================================================

# Install required packages
# !pip install torch transformers bitsandbytes accelerate

# Mount Google Drive first
from google.colab import drive
drive.mount('/content/drive')

# Clone the repo to import in Colab its packages from GitHub
# !git clone https://github.com/Joe-Occhipinti/unfaithfulness_steering.git
import os
if not os.path.exists('/content/unfaithfulness_steering'):
    # !git clone https://github.com/Joe-Occhipinti/unfaithfulness_steering.git
    pass
else:
    print("Repo already cloned.")

os.chdir('/content/unfaithfulness_steering')

# Authenticate in GitHub
# !git config --global user.email "occhidipinti00@gmail.com"
# !git config --global user.name "Joe Occhipinti"

# Put your GitHub token in Colab secrets
from google.colab import userdata
try:
    GITHUB_TOKEN = userdata.get('Colab')
    repo_url = f"https://{GITHUB_TOKEN}@github.com/Joe-Occhipinti/unfaithfulness_steering.git"
except Exception as e:
    print(f"Warning: Could not get Colab secret: {e}")

# =============================================================================
# SCRIPT LOGIC
# =============================================================================

import json
import torch
import pickle
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer
from datetime import datetime

# =============================================================================
# CONFIGURATION
# =============================================================================

# Model ID
MODEL_ID = "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"

# Input file (in Drive)
# Assuming the JSONL is uploaded to Drive or inside the repo
# Adjust this path as needed
INPUT_FILE = "/content/drive/MyDrive/unfaithfulness_steering/synthetic_F_vs_U_2025-10-31.jsonl"

# Output directory (in Drive)
OUTPUT_DIR = "/content/drive/MyDrive/unfaithfulness_steering/contrastive_vectors_off_policy_2nd_20-12-2025"

# =============================================================================
# FUNCTIONS
# =============================================================================

def load_contrastive_data(jsonl_file):
    """
    Loads contrastive prompts from a JSONL file.
    Expected structure: {"id": 1, "faithfulness": "...", "unfaithfulness": "..."}
    """
    print(f"Loading data from {jsonl_file}...")
    data = []
    with open(jsonl_file, 'r', encoding='utf-8') as f:
        for line in f:
            try:
                record = json.loads(line)
                if 'faithfulness' in record and 'unfaithfulness' in record:
                    data.append(record)
            except json.JSONDecodeError:
                print(f"Skipping malformed line")
    print(f"Loaded {len(data)} pairs.")
    return data

def extract_activations(data, model, tokenizer, device):
    """
    Extracts last token activations for both faithful and unfaithful prompts.
    """
    print("Extracting activations...")
    
    # Structure:
    # {
    #   "faithfulness_prompts": { id: { layer_idx: tensor } },
    #   "unfaithfulness_prompts": { id: { layer_idx: tensor } }
    # }
    dataset = {
        "faithfulness_prompts": {},
        "unfaithfulness_prompts": {}
    }
    
    for item in tqdm(data, desc="Processing prompts"):
        item_id = item.get('id')
        
        # Process both types
        for key in ['faithfulness', 'unfaithfulness']:
            text = item[key]
            
            # Tokenize
            inputs = tokenizer(text, return_tensors="pt").to(device)
            
            # Forward pass
            with torch.no_grad():
                outputs = model(**inputs, output_hidden_states=True)
            
            # Extract activations
            # outputs.hidden_states is a tuple of (layer_0, layer_1, ..., layer_N)
            layer_activations = {}
            for layer_idx, layer_tensor in enumerate(outputs.hidden_states):
                # Extract last token activation: [0, -1, :]
                # Move to CPU immediately to save GPU memory
                activation = layer_tensor[0, -1, :].cpu()
                
                # Store
                layer_activations[layer_idx] = activation
            
            # Add to dataset
            target_dict = dataset[f"{key}_prompts"]
            target_dict[item_id] = layer_activations
            
    return dataset

def compute_vectors(dataset):
    """
    Computes steering vectors: Mean(Faithful) - Mean(Unfaithful).
    Discards Layer 0 (Embeddings) and shifts indices (Layer 1 -> 0).
    """
    print("Computing steering vectors...")
    
    faithful_dict = dataset["faithfulness_prompts"]
    unfaithful_dict = dataset["unfaithfulness_prompts"]
    
    # Get all layer indices from the first item
    first_id = next(iter(faithful_dict))
    all_layers = sorted(faithful_dict[first_id].keys())
    
    steering_vectors = {}
    layer_stats = {}
    
    for layer_idx in all_layers:
        # Skip Layer 0 (Embeddings)
        if layer_idx == 0:
            continue
            
        # Collect all vectors for this layer
        f_vectors = [d[layer_idx] for d in faithful_dict.values()]
        u_vectors = [d[layer_idx] for d in unfaithful_dict.values()]
        
        if not f_vectors or not u_vectors:
            continue
            
        # Stack and mean
        f_tensor = torch.stack(f_vectors)
        u_tensor = torch.stack(u_vectors)
        
        f_mean = f_tensor.mean(dim=0)
        u_mean = u_tensor.mean(dim=0)
        
        # Difference
        vector = f_mean - u_mean
        
        # Shift index: Layer 1 -> 0
        new_layer_idx = layer_idx - 1
        steering_vectors[new_layer_idx] = vector
        
        layer_stats[new_layer_idx] = {
            "original_layer": layer_idx,
            "vector_norm": vector.norm().item(),
            "faithful_norm": f_mean.norm().item(),
            "unfaithful_norm": u_mean.norm().item()
        }
        
    return steering_vectors, layer_stats

# =============================================================================
# MAIN EXECUTION
# =============================================================================

def main():
    # Setup
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Using device: {device}")
    
    # Ensure output directory exists
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # Load Data
    if not os.path.exists(INPUT_FILE):
        print(f"Error: Input file not found at {INPUT_FILE}")
        print("Please check the path in Google Drive.")
        return

    data = load_contrastive_data(INPUT_FILE)
    if not data:
        print("No data found. Exiting.")
        return

    # Load Model
    print(f"Loading model: {MODEL_ID}")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID, 
        torch_dtype=torch.float16 if device == "cuda" else torch.float32,
        device_map="auto" if device == "cuda" else None
    )
    model.eval()
    
    # Extract
    activations_dataset = extract_activations(data, model, tokenizer, device)
    
    # Save Activations
    activations_file = os.path.join(OUTPUT_DIR, "activations_dataset.pkl")
    print(f"Saving activations to {activations_file}...")
    with open(activations_file, 'wb') as f:
        pickle.dump(activations_dataset, f)
        
    # Compute Vectors
    steering_vectors, layer_stats = compute_vectors(activations_dataset)
    
    # Save Vectors
    vectors_file = os.path.join(OUTPUT_DIR, "steering_vectors.pkl")
    
    output_data = {
        "steering_vectors": steering_vectors,
        "computation_stats": {
            "layer_stats": layer_stats,
            "sample_count": len(data)
        },
        "metadata": {
            "description": "Contrastive steering vectors (Faithful - Unfaithful)",
            "source_file": INPUT_FILE,
            "model": MODEL_ID,
            "computation_date": datetime.now().isoformat()
        }
    }
    
    print(f"Saving steering vectors to {vectors_file}...")
    with open(vectors_file, 'wb') as f:
        pickle.dump(output_data, f)
        
    print("Done!")
    print(f"Results saved to Drive: {OUTPUT_DIR}")

if __name__ == "__main__":
    main()
